version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.0
      - image: mysql/mysql-server:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_USER: voicera
          MYSQL_PASSWORD: voicera
          MYSQL_DATABASE: voicera

jobs:
  dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - app-{{ .Branch }}-
            - app-
      - run:
          name: Install packages
          command: npm ci
          working_directory: ./code
      - save_cache:
          paths:
            - ~/project/code/node_modules
          key: app-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
        name: Run tests
        command: npm test
        working_directory: ./code

      - persist_to_workspace:
          root: ~/project
          paths: code

  build:
    executor: node
    working_directory: ./code
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build application
          command: npm run build

  check:
    executor: node
    working_directory: ./code
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Check code style
          command: npm run check

  # test:
  #   executor: node
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run:
  #         name: Check MySQL version
  #         command: mysql -V
  #     - run:
  #         name: Run tests
  #         command: npm test
  #         working_directory: ./code

workflows:
  build-app:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - check:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies