version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.0

commands:
  install_dependencies:
    description: 'Installs and caches project dependencies.'
    steps:
      - checkout
      - combine_package_lock:
          filename: combined-package-lock.txt
      - restore_cache:
          keys:
            - app-{{ checksum "./code/package-lock.json" }}-{{ checksum "./code/combined-package-lock.txt" }}
            - app-
      - run:
          name: Install root dependencies
          command: npm install
          working_directory: ./code
      - run:
          name: Install packages dependencies
          command: npm run bootstrap
          working_directory: ./code
      - save_cache:
          paths:
            - ~/project/code/node_modules
            - ~/project/code/app/node_modules
            - ~/project/code/cli/node_modules
            - ~/project/code/utils/node_modules
          key: app-{{ checksum "./code/package-lock.json" }}-{{ checksum "./code/combined-package-lock.txt" }}

  combine_package_lock:
    description: 'Concatenate all package-lock.json files into single file used as checksum source for part of caching key.'
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna la -a | awk -F packages '{printf "\".%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>
          working_directory: ./code

jobs:
  build:
    executor: node
    steps:
      - install_dependencies
      - run:
          name: Build application
          command: npm run build
          working_directory: ./code/app

  inspect:
    executor: node
    steps:
      - install_dependencies
      - run:
          name: Run ESLint
          command: npm run eslint -- --max-warnings 0
          working_directory: ./code
      - run:
          name: Run Stylelint
          command: npm run stylelint
          working_directory: ./code

  test:
    docker:
      - image: cimg/node:14.0
      - image: mysql/mysql-server:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_USER: munity
          MYSQL_PASSWORD: munity
          MYSQL_DATABASE: munity
    steps:
      - install_dependencies
      - run:
          name: Run tests
          command: npm test
          working_directory: ./code

workflows:
  build-inspect-test:
    jobs:
      - build
      - inspect
      - test
