version: 2.1

jobs:
  build:
    docker:
      - image: node:14-alpine
      - image: circleci/mysql:8.0
        environment:
          - MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          - MYSQL_HOST: $MYSQL_HOST
          - MYSQL_USER: $MYSQL_USER
          - MYSQL_PASSWORD: $MYSQL_PASSWORD
          - MYSQL_DATABASE: $MYSQL_DATABASE
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
          working_directory: ./code
      # - run:
      #     name: Build application
      #     command: npm run build
      #     working_directory: ./code
      - run:
          name: Run tests
          command: npm test
          working_directory: ./code

workflows:
  build-app:
    jobs:
      - build
