version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build application
          command: next build
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm

workflows:
  orb-free-workflow:
    jobs:
      - test
