version: 2.1

jobs:
  build:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
          working_directory: ./code
      - run:
          name: Build application
          command: next build
          working_directory: ./code

workflows:
  build-app:
    jobs:
      - build
