version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0
      - image: mysql/mysql-server:8.0
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_HOST: localhost
          MYSQL_USER: voicera
          MYSQL_PASSWORD: voicera
          MYSQL_DATABASE: voicera
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - app-{{ .Branch }}-
            - app-
      - run:
          name: Install packages
          command: npm ci
          working_directory: ./code
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: app-{{ .Branch }}-{{ checksum "package-lock.json" }}


      # - run:
      #     name: Build application
      #     command: npm run build
      #     working_directory: ./code

      - run:
          name: Run tests
          command: npm test
          working_directory: ./code

workflows:
  build-app:
    jobs:
      - build
