version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.0

commands:
  install_dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "./code/package-lock.json" }}
            - app-
      - run:
          name: Install packages
          command: npm install
          working_directory: ./code
      - save_cache:
          paths:
            - ~/project/code/node_modules
          key: app-{{ checksum "./code/package-lock.json" }}

jobs:
  build:
    executor: node
    steps:
      - install_dependencies
      - run:
          name: Build application
          command: npm run build
          working_directory: ./code

  inspect:
    executor: node
    steps:
      - install_dependencies
      - run:
          name: Run ESLint
          command: npm run eslint -- --max-warnings 0
          working_directory: ./code
      - run:
          name: Run Stylelint
          command: npm run stylelint
          working_directory: ./code

  test:
    docker:
      - image: cimg/node:14.0
      - image: mysql/mysql-server:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_USER: voicera
          MYSQL_PASSWORD: voicera
          MYSQL_DATABASE: voicera
    steps:
      - install_dependencies
      - run:
          name: Run tests
          command: npm test
          working_directory: ./code

workflows:
  build-inspect-test:
    jobs:
      - build
      - inspect
      - test