version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0
      - image: mysql/mysql-server:8.0
        environment:
          - MYSQL_ROOT_PASSWORD: pwd
          - MYSQL_HOST: localhost
          - MYSQL_USER: user
          - MYSQL_PASSWORD: pwd
          - MYSQL_DATABASE: complaints_test
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      # - run:
      #     name: Install MySQL CLI
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install default-mysql-client

      - restore_cache:
          keys:
            - app-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - app-{{ .Branch }}-
            - app-
      
      - run:
          name: Install packages
          command: npm ci
          working_directory: ./code

      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: app-{{ .Branch }}-{{ checksum "package-lock.json" }}


      # - run:
      #     name: Build application
      #     command: npm run build
      #     working_directory: ./code

      - run:
          name: Ingest example data
          command: npm run ingest -- 10
          working_directory: ./code

      # - run:
      #     name: Run tests
      #     command: npm test
      #     working_directory: ./code

workflows:
  build-app:
    jobs:
      - build
